#!/bin/bash

# Create new files based on templates from $HOME/.templates

if [[ $# -eq 0 ]]; then
    template=$HOME/.templates/$(ls $HOME/.templates | fzf --color 16)
elif [[ $# -eq 1 ]]; then
    template=$HOME/.templates/$(ls $HOME/.templates | fzf -f $1 | head -n 1)
    read -p "Target: " target
elif [[ $# -eq 2 ]]; then
    template=$HOME/.templates/$(ls $HOME/.templates | fzf -f $1 | head -n 1)
    target=$2
else
    echo "Usage: filenew [template] [target]"
    exit 1
fi

if [[ $target != "" ]]; then
    echo "No such template."
    exit 3
fi

if [[ $# -eq 0  || $# -eq 1 ]]; then
    read -p "Target: " target
elif [[ $# -eq 2 ]]; then
    target=$2
fi

if [[ -f $target ]]; then
    echo "I'm afraid I cannot let you do that, Dave."
    echo "This file already exists."
    exit 2
fi

cp $template $target
echo "Created File $target from Template $template."
