#!/bin/bash

# psync: Passwörter vom Passwort-Stick synchronisieren

PWD_UUID="66E2-2710"

##################

err_report() {
    echo "Error on line $1"
    notify-send -u critical "Error!"
    exit 1
}

trap 'err_report $LINENO' ERR

block_device="/dev/disk/by-uuid/${PWD_UUID}"
udisks_msg=$(udisksctl mount -o ro -b $block_device 2>&1)
udisks_status=$?
echo "udisksctl exited with message:"
echo $udisks_msg

if [ ! $udisks_status -eq 0 ]; then
    msg="psync exit with status code: $udisks_status. Nothing happened"
    echo "$msg"
    notify-send -u critical "$msg"
    exit $udisks_status
fi

mount_dir=$(echo $udisks_msg | awk '{print $4}' | tr -d .)

umask "077"
cp ~/Passwörter/Passwörter.kdbx ~/Passwörter/.psync_rollback_$(date +"%Y_%m_%d-%H:%M:%S").kdbx
rm -f ~/Passwörter/Passwörter.kdbx
cp $mount_dir/Passwörter.kdbx ~/Passwörter/Passwörter.kdbx

cp -r ~/.gnupg/ ~/Passwörter/.gnupg-rollback_$(date +"%Y_%m_%d-%H:%M:%S")
rm -rf ~/.gnupg/
cp -r $mount_dir/.gnupg ~/.gnupg
umount $block_device

echo "psync: Success"
notify-send "psync: Success"
